public class Cores {

    public string corFinal1(string amarelo, string azul){
        return amarelo + azul ;
    }
     public string resultado1(string resultadoFinal1){
		return resultadoFinal1;
     }
    
    public string corFinal2(string amarelo, string laranja){
        return amarelo + laranja ;
    }
     public string resultado2(string resultadoFinal2){
		return resultadoFinal2;
    }
}