//Cria 2 Listas 1 com valores Pares e outra com valores ímpares, utilizando um loop.

list <integer>  listaPar = new list<integer>();
list <integer> listaImpar = new list<integer>();
 
integer contPar = 2;
while(contpar < 22){
    listaPar.add(contPar);
	contPar+=2;
}
 
system.debug(listaPar);
 
integer contImpar = 1;
while(contImpar < 20 ){
    listaImpar.add(contImpar);
    contImpar+=2;
}
 
system.debug(listaImpar);
