public class Calc {
	
    public decimal somar(integer a, integer b){
        return a+b;
    }
    
    public decimal sub(integer a, integer b){
        return a-b;
    }
    
    public decimal div(integer a, integer b){
        return a/b;
    }
    
    public decimal mult(integer a, integer b){
        return a*b;
    }
    
    public decimal media(integer a, integer b){
        return ((a+b)/2);
    }
}