public class Calculadora {
    public integer soma(integer n1, integer n2){ 
        return n1 + n2;
    }


/*Calculadora calc = new Calculadora();

integer resultado = calc.soma(4,5);

system.debug('resultado é: '+resultado);*/

	public decimal somaDecimal(decimal num1, decimal num2){
    	return num1+num2;
}
/*Calculadora calc = new Calculadora();

decimal resultado = calc.somaDecimal(3.5, 4.5);

system.debug('resultado é: '+resultado); */
}